### ISSUE TITLE
How to get User in aurelia app

### ISSUE THREAD

**Issue by khuzemakanore** [shaunluttin/aurelia-open-id-connect-demos#5]
I am having trouble getting a user after the user is authenticated in IdentityServer.

So in home.ts I am adding following code :

`
import { autoinject, PLATFORM } from "aurelia-framework";
import { RouterConfiguration, Router } from "aurelia-router";
import { User } from "oidc-client";
import { OpenIdConnect, OpenIdConnectRoles } from "aurelia-open-id-connect";

@autoinject

export class Home {
    public user: User;
    public openIdConnect: OpenIdConnect;
    public userdata:any;

  constructor(private openIdConnect: OpenIdConnect) {
    this.openIdConnect = openIdConnect;
  }

  activate() {
    return this.openIdConnect.getUser().then((data: any) => (this.userdata = data));
  }
}
`

result I get is promise.pending. how to resolve it. 

Any help? Whats wrong I am doing here?

**Comment by shaunluttin** [comment]
Where are you seeing the `promise.pending`? For instance, are you seeing that within the `userdata` property?

**Comment by khuzemakanore** [comment]
Ok I resolved it by below code in home.ts -

```
  activate()
  {
    this.openIdConnect.getUser().then(function (user) {
      if (user) {
        console.log("User logged in", user.profile);
      }
      else {
        console.log("User not logged in");
      }
    });
  }
```

The above code is used from IdentityServer quickstart
